kind: pipeline
type: kubernetes
name: greeting
clone:
  disable: false
metadata:
  namespace: drone-builds
steps:
  - name: en
    image: alpine
    commands:
      - echo hello
      - echo world
      - ping dl-cdn.alpinelinux.org -c 3
      - apk add curl --no-cache
      - curl github.com
      - uname -a
  - name: es
    image: alpine
    commands:
      - export TEST_VALUE=$TEST
      - echo $TEST_VALUE
      - echo mundo
      - echo $VALUE
