kind: pipeline
type: kubernetes
name: greeting
metadata:
  namespace: drone-builds
steps:
  - name: en
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: es
    image: alpine
    environment:
      TEST:
        from_secret: DRONE_DOCKER_USERNAME
    commands:
      - echo $TEST
      - echo "Hello"
      - printenv

---
kind: secret
name: DRONE_DOCKER_USERNAME
get:
  path: secret/data/infra_secrets/global_secrets
  name: DOCKER_USERNAME
# kind: pipeline
# type: kubernetes
# name: greeting
# clone:
#   disable: false
# metadata:
#   namespace: drone-builds
# steps:
#   - name: en
#     image: alpine
#     commands:
#       - echo hello
#       - echo world
#       - ping dl-cdn.alpinelinux.org -c 3
#       - apk add curl --no-cache
#       - curl github.com
#       - uname -a
#   - name: es
#     image: alpine
#     commands:
#       - export TEST_VALUE=$TEST
#       - echo $TEST_VALUE
#       - echo mundo
#       - echo $VALUE
