kind: pipeline
type: kubernetes
name: greeting

steps:
  - name: en
    image: alpine
    commands:
      - echo hello
      - echo world

  - name: es
    image: alpine
    commands:
      - export TEST_VALUE=$TEST
      - echo $TEST_VALUE
      - echo mundo
      - echo $VALUE
