kind: pipeline
name: greeting

steps:
  - name: en
    image: alpine
    commands:
      - echo hello
      - echo world

  - name: es
    image: alpine
    commands:
      - echo $test
      - echo mundo
    environment:
      test:
        from_secret: test

---
kind: secret
name: test
get:
  path: secret/data/tester
  name: tester
